class AirportRecord {
  const AirportRecord({
    required this.code,
    required this.name,
    required this.latitude,
    required this.longitude,
  });

  final String code;
  final String name;
  final double latitude;
  final double longitude;
}

class AirportCatalog {
  static const Map<String, AirportRecord> airports = {
    'ATL': AirportRecord(
      code: 'ATL',
      name: 'Atlanta Hartsfield-Jackson',
      latitude: 33.6407,
      longitude: -84.4277,
    ),
    'LAX': AirportRecord(
      code: 'LAX',
      name: 'Los Angeles International',
      latitude: 33.9416,
      longitude: -118.4085,
    ),
    'ORD': AirportRecord(
      code: 'ORD',
      name: "Chicago O'Hare",
      latitude: 41.9742,
      longitude: -87.9073,
    ),
    'DFW': AirportRecord(
      code: 'DFW',
      name: 'Dallas/Fort Worth',
      latitude: 32.8998,
      longitude: -97.0403,
    ),
    'DEN': AirportRecord(
      code: 'DEN',
      name: 'Denver International',
      latitude: 39.8561,
      longitude: -104.6737,
    ),
    'JFK': AirportRecord(
      code: 'JFK',
      name: 'New York JFK',
      latitude: 40.6413,
      longitude: -73.7781,
    ),
    'SFO': AirportRecord(
      code: 'SFO',
      name: 'San Francisco International',
      latitude: 37.6213,
      longitude: -122.3790,
    ),
    'SEA': AirportRecord(
      code: 'SEA',
      name: 'Seattle-Tacoma',
      latitude: 47.4502,
      longitude: -122.3088,
    ),
    'LAS': AirportRecord(
      code: 'LAS',
      name: 'Las Vegas McCarran',
      latitude: 36.0840,
      longitude: -115.1537,
    ),
    'MCO': AirportRecord(
      code: 'MCO',
      name: 'Orlando International',
      latitude: 28.4312,
      longitude: -81.3081,
    ),
    'EWR': AirportRecord(
      code: 'EWR',
      name: 'Newark Liberty',
      latitude: 40.6895,
      longitude: -74.1745,
    ),
    'MSP': AirportRecord(
      code: 'MSP',
      name: 'Minneapolis-St. Paul',
      latitude: 44.8848,
      longitude: -93.2223,
    ),
    'BOS': AirportRecord(
      code: 'BOS',
      name: 'Boston Logan',
      latitude: 42.3656,
      longitude: -71.0096,
    ),
    'DTW': AirportRecord(
      code: 'DTW',
      name: 'Detroit Metropolitan',
      latitude: 42.2125,
      longitude: -83.3534,
    ),
    'PHL': AirportRecord(
      code: 'PHL',
      name: 'Philadelphia International',
      latitude: 39.8729,
      longitude: -75.2437,
    ),
    'LGA': AirportRecord(
      code: 'LGA',
      name: 'New York LaGuardia',
      latitude: 40.7769,
      longitude: -73.8740,
    ),
    'PHX': AirportRecord(
      code: 'PHX',
      name: 'Phoenix Sky Harbor',
      latitude: 33.4352,
      longitude: -112.0101,
    ),
    'IAH': AirportRecord(
      code: 'IAH',
      name: 'Houston George Bush',
      latitude: 29.9902,
      longitude: -95.3368,
    ),
    'MIA': AirportRecord(
      code: 'MIA',
      name: 'Miami International',
      latitude: 25.7959,
      longitude: -80.2870,
    ),
    'CLT': AirportRecord(
      code: 'CLT',
      name: 'Charlotte Douglas',
      latitude: 35.2140,
      longitude: -80.9431,
    ),
    'SAN': AirportRecord(
      code: 'SAN',
      name: 'San Diego International',
      latitude: 32.7338,
      longitude: -117.1933,
    ),
    'PDX': AirportRecord(
      code: 'PDX',
      name: 'Portland International',
      latitude: 45.5898,
      longitude: -122.5951,
    ),
    'YYZ': AirportRecord(
      code: 'YYZ',
      name: 'Toronto Pearson',
      latitude: 43.6777,
      longitude: -79.6248,
    ),
    'YVR': AirportRecord(
      code: 'YVR',
      name: 'Vancouver International',
      latitude: 49.1939,
      longitude: -123.1844,
    ),
    'YUL': AirportRecord(
      code: 'YUL',
      name: 'Montreal-Trudeau',
      latitude: 45.4657,
      longitude: -73.7448,
    ),
    'MEX': AirportRecord(
      code: 'MEX',
      name: 'Mexico City International',
      latitude: 19.4363,
      longitude: -99.0721,
    ),
    'LHR': AirportRecord(
      code: 'LHR',
      name: 'London Heathrow',
      latitude: 51.4700,
      longitude: -0.4543,
    ),
    'CDG': AirportRecord(
      code: 'CDG',
      name: 'Paris Charles de Gaulle',
      latitude: 49.0097,
      longitude: 2.5479,
    ),
    'AMS': AirportRecord(
      code: 'AMS',
      name: 'Amsterdam Schiphol',
      latitude: 52.3105,
      longitude: 4.7683,
    ),
    'FRA': AirportRecord(
      code: 'FRA',
      name: 'Frankfurt Airport',
      latitude: 50.0379,
      longitude: 8.5622,
    ),
    'MAD': AirportRecord(
      code: 'MAD',
      name: 'Madrid-Barajas',
      latitude: 40.4983,
      longitude: -3.5676,
    ),
    'BCN': AirportRecord(
      code: 'BCN',
      name: 'Barcelona-El Prat',
      latitude: 41.2974,
      longitude: 2.0833,
    ),
    'FCO': AirportRecord(
      code: 'FCO',
      name: 'Rome Fiumicino',
      latitude: 41.8003,
      longitude: 12.2389,
    ),
    'MUC': AirportRecord(
      code: 'MUC',
      name: 'Munich Airport',
      latitude: 48.3537,
      longitude: 11.7750,
    ),
    'LGW': AirportRecord(
      code: 'LGW',
      name: 'London Gatwick',
      latitude: 51.1537,
      longitude: -0.1821,
    ),
    'ZRH': AirportRecord(
      code: 'ZRH',
      name: 'Zurich Airport',
      latitude: 47.4582,
      longitude: 8.5481,
    ),
    'IST': AirportRecord(
      code: 'IST',
      name: 'Istanbul Airport',
      latitude: 41.2753,
      longitude: 28.7519,
    ),
    'VIE': AirportRecord(
      code: 'VIE',
      name: 'Vienna International',
      latitude: 48.1103,
      longitude: 16.5697,
    ),
    'CPH': AirportRecord(
      code: 'CPH',
      name: 'Copenhagen Airport',
      latitude: 55.6180,
      longitude: 12.6508,
    ),
    'OSL': AirportRecord(
      code: 'OSL',
      name: 'Oslo Gardermoen',
      latitude: 60.1939,
      longitude: 11.1004,
    ),
    'ARN': AirportRecord(
      code: 'ARN',
      name: 'Stockholm Arlanda',
      latitude: 59.6519,
      longitude: 17.9186,
    ),
    'DUB': AirportRecord(
      code: 'DUB',
      name: 'Dublin Airport',
      latitude: 53.4213,
      longitude: -6.2701,
    ),
    'MAN': AirportRecord(
      code: 'MAN',
      name: 'Manchester Airport',
      latitude: 53.3537,
      longitude: -2.2750,
    ),
    'EDI': AirportRecord(
      code: 'EDI',
      name: 'Edinburgh Airport',
      latitude: 55.9500,
      longitude: -3.3725,
    ),
    'LIS': AirportRecord(
      code: 'LIS',
      name: 'Lisbon Portela',
      latitude: 38.7742,
      longitude: -9.1342,
    ),
    'ATH': AirportRecord(
      code: 'ATH',
      name: 'Athens International',
      latitude: 37.9364,
      longitude: 23.9445,
    ),
    'BRU': AirportRecord(
      code: 'BRU',
      name: 'Brussels Airport',
      latitude: 50.9010,
      longitude: 4.4856,
    ),
    'PRG': AirportRecord(
      code: 'PRG',
      name: 'Prague Vaclav Havel',
      latitude: 50.1008,
      longitude: 14.2632,
    ),
    'WAW': AirportRecord(
      code: 'WAW',
      name: 'Warsaw Chopin',
      latitude: 52.1657,
      longitude: 20.9671,
    ),
    'BUD': AirportRecord(
      code: 'BUD',
      name: 'Budapest Ferenc Liszt',
      latitude: 47.4297,
      longitude: 19.2611,
    ),
    'VCE': AirportRecord(
      code: 'VCE',
      name: 'Venice Marco Polo',
      latitude: 45.5053,
      longitude: 12.3519,
    ),
    'MXP': AirportRecord(
      code: 'MXP',
      name: 'Milan Malpensa',
      latitude: 45.6306,
      longitude: 8.7231,
    ),
    'NAP': AirportRecord(
      code: 'NAP',
      name: 'Naples International',
      latitude: 40.8860,
      longitude: 14.2908,
    ),
    'HND': AirportRecord(
      code: 'HND',
      name: 'Tokyo Haneda',
      latitude: 35.5494,
      longitude: 139.7798,
    ),
    'NRT': AirportRecord(
      code: 'NRT',
      name: 'Tokyo Narita',
      latitude: 35.7720,
      longitude: 140.3929,
    ),
    'PEK': AirportRecord(
      code: 'PEK',
      name: 'Beijing Capital',
      latitude: 40.0801,
      longitude: 116.5846,
    ),
    'PVG': AirportRecord(
      code: 'PVG',
      name: 'Shanghai Pudong',
      latitude: 31.1443,
      longitude: 121.8083,
    ),
    'HKG': AirportRecord(
      code: 'HKG',
      name: 'Hong Kong International',
      latitude: 22.3080,
      longitude: 113.9185,
    ),
    'SIN': AirportRecord(
      code: 'SIN',
      name: 'Singapore Changi',
      latitude: 1.3644,
      longitude: 103.9915,
    ),
    'ICN': AirportRecord(
      code: 'ICN',
      name: 'Seoul Incheon',
      latitude: 37.4602,
      longitude: 126.4407,
    ),
    'BKK': AirportRecord(
      code: 'BKK',
      name: 'Bangkok Suvarnabhumi',
      latitude: 13.6900,
      longitude: 100.7501,
    ),
    'KUL': AirportRecord(
      code: 'KUL',
      name: 'Kuala Lumpur International',
      latitude: 2.7456,
      longitude: 101.7072,
    ),
    'DEL': AirportRecord(
      code: 'DEL',
      name: 'Delhi Indira Gandhi',
      latitude: 28.5562,
      longitude: 77.1000,
    ),
    'BOM': AirportRecord(
      code: 'BOM',
      name: 'Mumbai Chhatrapati Shivaji',
      latitude: 19.0896,
      longitude: 72.8656,
    ),
    'SYD': AirportRecord(
      code: 'SYD',
      name: 'Sydney Kingsford Smith',
      latitude: -33.9399,
      longitude: 151.1753,
    ),
    'MEL': AirportRecord(
      code: 'MEL',
      name: 'Melbourne Airport',
      latitude: -37.6690,
      longitude: 144.8410,
    ),
    'AKL': AirportRecord(
      code: 'AKL',
      name: 'Auckland Airport',
      latitude: -37.0082,
      longitude: 174.7850,
    ),
    'MNL': AirportRecord(
      code: 'MNL',
      name: 'Manila Ninoy Aquino',
      latitude: 14.5086,
      longitude: 121.0194,
    ),
    'CGK': AirportRecord(
      code: 'CGK',
      name: 'Jakarta Soekarno-Hatta',
      latitude: -6.1275,
      longitude: 106.6537,
    ),
    'TPE': AirportRecord(
      code: 'TPE',
      name: 'Taipei Taoyuan',
      latitude: 25.0797,
      longitude: 121.2342,
    ),
    'CAN': AirportRecord(
      code: 'CAN',
      name: 'Guangzhou Baiyun',
      latitude: 23.3924,
      longitude: 113.2988,
    ),
    'SHA': AirportRecord(
      code: 'SHA',
      name: 'Shanghai Hongqiao',
      latitude: 31.1979,
      longitude: 121.3364,
    ),
    'DXB': AirportRecord(
      code: 'DXB',
      name: 'Dubai International',
      latitude: 25.2532,
      longitude: 55.3657,
    ),
    'DOH': AirportRecord(
      code: 'DOH',
      name: 'Doha Hamad International',
      latitude: 25.2731,
      longitude: 51.6080,
    ),
    'AUH': AirportRecord(
      code: 'AUH',
      name: 'Abu Dhabi International',
      latitude: 24.4330,
      longitude: 54.6511,
    ),
    'CAI': AirportRecord(
      code: 'CAI',
      name: 'Cairo International',
      latitude: 30.1219,
      longitude: 31.4056,
    ),
    'TLV': AirportRecord(
      code: 'TLV',
      name: 'Tel Aviv Ben Gurion',
      latitude: 32.0114,
      longitude: 34.8867,
    ),
    'GRU': AirportRecord(
      code: 'GRU',
      name: 'Sao Paulo Guarulhos',
      latitude: -23.4356,
      longitude: -46.4731,
    ),
    'GIG': AirportRecord(
      code: 'GIG',
      name: 'Rio de Janeiro Galeao',
      latitude: -22.8099,
      longitude: -43.2505,
    ),
    'SCL': AirportRecord(
      code: 'SCL',
      name: 'Santiago International',
      latitude: -33.3930,
      longitude: -70.7858,
    ),
    'BOG': AirportRecord(
      code: 'BOG',
      name: 'Bogota El Dorado',
      latitude: 4.7016,
      longitude: -74.1469,
    ),
    'LIM': AirportRecord(
      code: 'LIM',
      name: 'Lima Jorge Chavez',
      latitude: -12.0219,
      longitude: -77.1143,
    ),
    'EZE': AirportRecord(
      code: 'EZE',
      name: 'Buenos Aires Ezeiza',
      latitude: -34.8222,
      longitude: -58.5358,
    ),
    'JNB': AirportRecord(
      code: 'JNB',
      name: 'Johannesburg OR Tambo',
      latitude: -26.1392,
      longitude: 28.2460,
    ),
    'CPT': AirportRecord(
      code: 'CPT',
      name: 'Cape Town International',
      latitude: -33.9715,
      longitude: 18.6021,
    ),
    'NBO': AirportRecord(
      code: 'NBO',
      name: 'Nairobi Jomo Kenyatta',
      latitude: -1.3192,
      longitude: 36.9278,
    ),
    'ADD': AirportRecord(
      code: 'ADD',
      name: 'Addis Ababa Bole',
      latitude: 8.9779,
      longitude: 38.7992,
    ),
  };

  static AirportRecord? lookup(String code) {
    return airports[code.trim().toUpperCase()];
  }
}
